name: test-and-publish-package

on:
  workflow_call:
    inputs:
      install-eplus-920:
        description: "Should I install Energy Plus 9.2.0 ?"
        required: false
        type: boolean
    secrets:
      # mandatory
      ADMIN_GITHUB_TOKEN:
        description: "Openergy admin github token"
        required: true
      AZURE_CONDA_CHANNEL_KEY:
        description: "Azure Storage Account key"
        required: true

      # optional
      CONDA_CHANNEL_SYSADMIN_URL:
        description: "URL containing sysadmin password to use Openergy's private conda channel."
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.build-package.outputs.build-version }}
    steps:
      - name: build package
        id: build-package
        uses: ./actions/opypackage-build-v01
        with:
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          conda-channel-sysadmin-url: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}

  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: test package
        uses: ./actions/opypackage-test-v01
        with:
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          build-version: ${{ needs.build.outputs.build-version }}
          conda-channel-sysadmin-url: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}
          install-eplus-920: ${{ inputs.install-eplus-920 }}

  version:
    needs: [ build, test ]
    runs-on: ubuntu-latest
    if: needs.build.outputs.build-version != 'next'
    steps:
      - name: version repo
        uses: ./actions/opypackage-version-v01
        with:
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          build-version: ${{ needs.build.outputs.build-version }}
          conda-channel-sysadmin-url: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}

  publish:
    needs: [ build, test, version ]
    runs-on: ubuntu-latest
    steps:
      - name: publish package
        uses: ./actions/opypackage-conda-publish-v01
        with:
          azure-conda-channel-key: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
