name: Build and publish openergy python package to pypi
description: package must have been correctly versioned
inputs:
  # mandatory
  admin-github-token:
    description: Openergy admin github token
    required: true
  pypi-openergy-password:
    description: password of openergy's pypi account
    required: true

  # optional
  python-requirement:
    description: Specific python requirement to install (for example "=3.7.0" or ">=3.7,<3.8") ?
    required: false
    default: ">=3.8"

# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
runs:
  using: composite
  steps:
    - name: checkout repo # automatically on push branch (must have been versioned previously)
      uses: actions/checkout@v4
      with:
        path: repo  # Relative path under $GITHUB_WORKSPACE to place the repository
        token: ${{ inputs.admin-github-token }}  # we want push to be done by Openergy Admin, for branch protection

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-requirement }}

    - name: install python packages
      shell: bash -l {0}
      working-directory: ${{ github.workspace }}/repo
      run: python -m pip install build

    - name: build a binary wheel and a source tarball
      shell: bash -l {0}
      working-directory: ${{ github.workspace }}/repo
      run: python -m build --sdist --wheel --outdir dist/

    - name: Upload release to PyPI
      permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: openergy
          password: ${{ inputs.pypi-openergy-password }}
          packages_dir: ${{ github.workspace }}/repo/dist
