name: test-and-publish-package

on:
  workflow_call:
    inputs:
      # optional
      install-eplus-920:
        description: Should I install Energy Plus 9.2.0 ?
        required: false
        type: boolean

      install-eplus-2210:
        description: Should I install Energy Plus 22.1.0 ?
        required: false
        type: boolean

      python-conda-requirement:
        description: Specific python requirement to install with conda (for example "=3.7.0" or ">=3.7,<3.8") ?
        required: false
        type: string
        default: ">=3.7,<3.8"

      python-pip-requirement:
        description: Specific python requirement to install with pip (for example "=3.7.0" or ">=3.7,<3.8") ?
        required: false
        type: string
        default: ">=3.7"

      publish-to-pypi:
        description: Should I publish to Pypi ? (! only for public packages !)
        required: false
        type: boolean
        default: false

    secrets:
      # mandatory
      ADMIN_GITHUB_TOKEN:
        description: Openergy admin github token
        required: true
      AZURE_CONDA_CHANNEL_KEY:
        description: Azure Storage Account key
        required: true

      # optional
      CONDA_CHANNEL_SYSADMIN_URL:
        description: URL containing sysadmin password to use Openergy's private conda channel.
        required: false
      PYPI_OPENERGY_PASSWORD:
        description: openergy's pypi account password (only if publish to pypi)
        required: false

jobs:
  conda-build:
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.build-package.outputs.build-version }}
    steps:
      - name: build package
        id: build-package
        uses: openergy/ogithub-actions/actions/opypackage-conda-build-v04@master
        with:
          python-requirement: ${{ inputs.python-conda-requirement }}
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          conda-channel-sysadmin-url: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}

  conda-test:
    needs: [ conda-build ]
    runs-on: ubuntu-latest
    steps:
      - name: test package
        uses: openergy/ogithub-actions/actions/opypackage-conda-test-v01@master
        with:
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          python-requirement: ${{ inputs.python-conda-requirement }}
          build-version: ${{ needs.conda-build.outputs.build-version }}
          conda-channel-sysadmin-url: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}
          install-eplus-920: ${{ inputs.install-eplus-920 }}
          install-eplus-2210: ${{ inputs.install-eplus-2210 }}

  version:
    needs: [ conda-build, conda-test ]
    runs-on: ubuntu-latest
    if: needs.conda-build.outputs.build-version != 'next'
    steps:
      - name: version repo
        uses: openergy/ogithub-actions/actions/opy-version-v01@master
        with:
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          build-version: ${{ needs.conda-build.outputs.build-version }}

  pypi-publish:
    needs: [ conda-build, conda-test, version ]
    runs-on: ubuntu-latest
    if: ${{ inputs.publish-to-pypi }}
    steps:
      - name: publish package to pypi
        uses: openergy/ogithub-actions/actions/opypackage-pip-build-and-publish-v01@master
        with:
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          pypi-openergy-password: ${{ secrets.PYPI_OPENERGY_PASSWORD }}
          python-requirement: ${{ inputs.python-pip-requirement }}

  conda-publish:
    needs: [ conda-build, conda-test, version ]
    runs-on: ubuntu-latest
    steps:
      - name: publish package to private conda registry
        uses: openergy/ogithub-actions/actions/opypackage-conda-publish-v01@master
        with:
          azure-conda-channel-key: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
