name: reindex-conda-channel

on:
  workflow_dispatch

jobs:
  reindex:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: "prepare ubuntu"
        run: |
          set -e
          sudo apt-get update && sudo apt-get install -y curl software-properties-common libcurl3-gnutls

      - name: "install blobfuse"
        run: |
          set -e

          # https://docs.microsoft.com/en-us/windows-server/administration/Linux-Package-Repository-for-Microsoft-Software#ubuntu
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          sudo apt-add-repository https://packages.microsoft.com/ubuntu/20.04/prod
          sudo apt-get update

          # https://docs.microsoft.com/en-us/azure/storage/blobs/storage-how-to-mount-container-linux
          sudo apt-get install -y blobfuse

      - name: "configure blobfuse"
        run: |
          set -e

          # tmp dir
          mkdir ${{ github.workspace }}/blobfusetmp -p

          # connection info
          cat > ${{ github.workspace }}/fuse_connection.cfg <<EOL
          accountName condachannel
          accountKey ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
          containerName static

          EOL

          # local conda-build work directory
          mkdir /${{ github.workspace }}/conda-build

          # mount directory
          blobfuse /${{ github.workspace }}/conda-build --tmp-path=${{ github.workspace }}/blobfusetmp --config-file=/${{ github.workspace }}/fuse_connection.cfg -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120

      - name: "install miniconda with conda-build"
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          conda-build-version: "*"
          auto-activate-base: true
          activate-environment: ""

      - name: "update index"
        run: conda index conda-build
