name: test-and-publish-package

on:
  workflow_call:
    inputs:
      INSTALL_EPLUS_920:
        description: "Should I install Energy Plus 9.2.0 ?"
        required: false
        type: boolean
    secrets:
      CONDA_CHANNEL_SYSADMIN_URL:
        description: "URL containing sysadmin password to use Openergy's private conda channel."
        required: false
      AZURE_CONDA_CHANNEL_KEY:
        description: "Azure Storage Account key"
        required: true
      GITHUB_ADMIN_TOKEN:
        description: "Openergy admin github token"
        required: true
        type: text

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
        # https://github.com/marketplace/actions/setup-miniconda#important
        working-directory: ${{ github.workspace }}
    outputs:
      REPOSITORY_NAME: ${{ steps.set-repository-name.outputs.REPOSITORY_NAME }}
      VERSION: ${{ steps.set-version.outputs.VERSION }}
    steps:
      - name: "retrieve and store repository name"
        id: set-repository-name
        run: echo "::set-output name=REPOSITORY_NAME::${{ github.event.repository.name }}"

      - name: "checkout repo" # automatically on develop
        uses: actions/checkout@v2
        with:
          path: repo  # Relative path under $GITHUB_WORKSPACE to place the repository
          token: ${{ secrets.GITHUB_ADMIN_TOKEN }}  # we want push to be done by Openergy Admin, for branch protection

      - name: "configure git"
        run: |
          set -e
          git config --global user.name Openergy Admin
          git config --global user.email admin@openergy.fr
        working-directory: ${{ github.workspace }}/repo

      - name: "prepare conda cache"  # https://github.com/marketplace/actions/setup-miniconda#caching
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-${{ hashFiles('${{ github.workspace }}/repo/requirements.txt') }}

      - name: "retrieve version in RELEASE.md ('next' or version number)"
        id: set-version
        run: echo "::set-output name=VERSION::$(sed -n '0,/^##/s/## //p' RELEASE.md)"
        working-directory: ${{ github.workspace }}/repo

      - name: "prepare version.py"
        run: printf 'version = "${{ steps.set-version.outputs.VERSION }}"\n' > ./${{ steps.set-repository-name.outputs.REPOSITORY_NAME }}/version.py
        working-directory: ${{ github.workspace }}/repo

      - name: "add version"
        run: git add ./${{ steps.set-repository-name.outputs.REPOSITORY_NAME }}/version.py
        working-directory: ${{ github.workspace }}/repo

      - name: "install miniconda with conda-build"
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          conda-build-version: "*"
          auto-activate-base: true
          activate-environment: ""

      - name: "add openergy conda channel if secret was provided"
        run: |
          set -e
          [ -z ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }} ] || conda config --system --add channels ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}

      - name: "prepare build info"
        run: |
          set -e
          mkdir conda-build
          # download create_meta script
          wget https://raw.githubusercontent.com/openergy/github-actions-workflows/master/.github/workflows-resources/create_meta.py -P ${{ github.workspace }}
          # create meta
          python ${{ github.workspace }}/create_meta.py conda-build ${{ steps.set-repository-name.outputs.REPOSITORY_NAME }} false
        working-directory: ${{ github.workspace }}/repo

      - name: "build"
        run: conda-build . --croot ${{ github.workspace }}/conda-build-to-upload
        working-directory: ${{ github.workspace }}/repo/conda-build

      - name: "upload build"
        uses: actions/upload-artifact@v2
        with:
          name: conda-build
          path: ${{ github.workspace }}/conda-build-to-upload
          retention-days: 1

      - name: "commit to develop"
        run: |
          set -e
          git commit -m "[CI] updated version as ${{ steps.set-version.outputs.VERSION }}" || :
          # || : => works as try/except:pass (commit may fail in certain cases if code has not changed, \
          #  but it shouldn't be a problem)
          git push origin develop
        working-directory: ${{ github.workspace }}/repo

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
        # https://github.com/marketplace/actions/setup-miniconda#important
        working-directory: ${{ github.workspace }}
    needs: build
    steps:
      - name: "checkout repo"  # (automatically on develop)
        uses: actions/checkout@v2
        with:
          path: repo  # Relative path under $GITHUB_WORKSPACE to place the repository
          token: ${{ secrets.GITHUB_ADMIN_TOKEN }}  # we want push to be done by Openergy Admin, for branch protection

      - name: "configure git"
        run: |
          set -e
          git config --global user.name Openergy Admin
          git config --global user.email admin@openergy.fr
        working-directory: ${{ github.workspace }}/repo

      - name: "download build"
        uses: actions/download-artifact@v2
        with:
          name: conda-build
          path: ${{ github.workspace }}/conda-build

      - name: "prepare miniconda cache"
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-${{ hashFiles('${{ github.workspace }}/conda-build/**') }}

      - name: "install miniconda"
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: defaults,conda-forge

      - name: "add openergy conda channel if secret was provided"
        run: |
          set -e
          [ -z ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }} ] || conda config --system --add channels ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}

      - name: "install EnergyPlus 9.2.0 if required"
        if: ${{ inputs.INSTALL_EPLUS_920 }}
        run: |
          set -e
          wget -q https://github.com/NREL/EnergyPlus/releases/download/v9.2.0/EnergyPlus-9.2.0-921312fa1d-Linux-x86_64.sh
          echo "y\r" | sudo bash ./EnergyPlus-9.2.0-921312fa1d-Linux-x86_64.sh
          sudo rm ./EnergyPlus-9.2.0-921312fa1d-Linux-x86_64.sh

      - name: "install requirements"
        run: |
          set -e
          # package requirements
          mamba install -q -c ${{ github.workspace }}/conda-build ${{ needs.build.outputs.REPOSITORY_NAME }}=${{ needs.build.outputs.VERSION }}
          # tests requirements
          mamba install pytest pytest-cov

      - name: "copy and run tests"
        run: |
          set -e
          cp -r ${{ github.workspace }}/repo/tests ${{ github.workspace }}
          pytest tests  # fixme: manage coverage

  version:
    needs: [build, test]
    if: needs.build.outputs.VERSION != 'next'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
        # https://github.com/marketplace/actions/setup-miniconda#important
        working-directory: ${{ github.workspace }}
    steps:
      - name: "checkout repo"  # automatically on develop
        uses: actions/checkout@v2
        with:
          path: repo  # Relative path under $GITHUB_WORKSPACE to place the repository
          fetch-depth: 0  # must fetch all or merges will fail
          token: ${{ secrets.GITHUB_ADMIN_TOKEN }}  # we want push to be done by Openergy Admin, for branch protection

      - name: "configure git"
        run: |
          set -e
          git config --global user.name Openergy Admin
          git config --global user.email admin@openergy.fr
        working-directory: ${{ github.workspace }}/repo

      - name: "update branches and tags"
        run: |
          set -e

          # checkout develop
          git checkout develop
          git pull  # does not seem to be up to date (which is quite odd)

          # checkout master, merge develop, push master
          git checkout master
          git pull  # make sure it is up to date
          git merge --ff-only develop
          git push origin master

          # create and push version
          echo "Versioning to version ${{ needs.build.outputs.VERSION }}"
          git tag ${{ needs.build.outputs.VERSION }}
          git push origin ${{ needs.build.outputs.VERSION }}

          # checkout develop and merge master
          git checkout develop
          git merge master

          # add and commit the next version to RELEASE.md
          sed -i "0,/^##/s/##/## next\\n\\n##/" RELEASE.md
          git commit RELEASE.md -m "[CI] added ## next to RELEASE.md"

          # push develop
          git push origin develop

        working-directory: ${{ github.workspace }}/repo

  conda-upload:
    needs: [build, test, version]  # we want to make sure that versioning worked before uploading to conda channel
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: "download build"
        uses: actions/download-artifact@v2
        with:
          name: conda-build
          path: ${{ github.workspace }}/conda-build

      - name: "install and configure rclone"
        run: |
          set -e

          # https://rclone.org/install/
          wget -q https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip rclone-current-linux-amd64.zip
          cd rclone-*-linux-amd64

          # https://askubuntu.com/questions/1357549/how-to-install-rclone-in-ubuntu-without-root

          # prepare local installation directories
          mkdir ~/.local
          mkdir ~/.local/bin
          mkdir ~/.local/share
          mkdir ~/.local/share/man
          mkdir ~/.local/share/man/man1

          # copy rclone files
          cp rclone ~/.local/bin
          chmod +x ~/.local/bin/rclone
          cp rclone.1 ~/.local/share/man/man1/

          # create conf
          cat > ~/.rclone.conf <<EOL
          [condachannel]
          type = azureblob
          account = condachannel
          key = ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}

          EOL

      - name: "install miniconda with conda-build"
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          conda-build-version: "*"
          auto-activate-base: true
          activate-environment: ""

      - name: "download packages, update index and upload to channel"
        run: |
          set -e
          rclone copy condachannel:static conda-build
          conda index conda-build
          rclone copy conda-build condachannel:static
